---
# The name of the service. This will be used by other services to determine dependancy
name: 'ActionValidator'

# Module where the service is located
module: 'deckr.game.action_validator'

# Class that implements service
class: 'ActionValidator'
