# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client_message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2

import game_action_pb2
import util_pb2

# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='client_message.proto',
  package='',
  serialized_pb='\n\x14\x63lient_message.proto\x1a\x11game_action.proto\x1a\nutil.proto\"\x89\x02\n\rClientMessage\x12\x37\n\x0cmessage_type\x18\x01 \x02(\x0e\x32!.ClientMessage.ClientMessageTypes\x12&\n\x0e\x63reate_message\x18\x02 \x01(\x0b\x32\x0e.CreateMessage\x12\"\n\x0cjoin_message\x18\x03 \x01(\x0b\x32\x0c.JoinMessage\x12&\n\x0e\x61\x63tion_message\x18\x04 \x01(\x0b\x32\x0e.ActionMessage\"K\n\x12\x43lientMessageTypes\x12\n\n\x06\x43REATE\x10\x00\x12\x08\n\x04JOIN\x10\x01\x12\n\n\x06\x41\x43TION\x10\x02\x12\t\n\x05LEAVE\x10\x03\x12\x08\n\x04QUIT\x10\x04\"5\n\rCreateMessage\x12\x0f\n\x07variant\x18\x01 \x01(\t\x12\x13\n\x0bmax_players\x18\x02 \x01(\x05\"\x9b\x01\n\x0bJoinMessage\x12\x0f\n\x07game_id\x18\x01 \x02(\x05\x12,\n\x0b\x63lient_type\x18\x02 \x02(\x0e\x32\x17.JoinMessage.ClientType\x12$\n\rplayer_config\x18\x03 \x01(\x0b\x32\r.PlayerConfig\"\'\n\nClientType\x12\n\n\x06PLAYER\x10\x00\x12\r\n\tSPECTATOR\x10\x01\"\xdc\x02\n\rActionMessage\x12.\n\x0b\x61\x63tion_type\x18\x01 \x02(\x0e\x32\x19.ActionMessage.ActionType\x12\x19\n\x04play\x18\x02 \x01(\x0b\x32\x0b.PlayAction\x12)\n\x10\x61\x63tivate_ability\x18\x03 \x01(\x0b\x32\x0f.ActivateAction\x12\x32\n\x11\x64\x65\x63lare_attackers\x18\x04 \x01(\x0b\x32\x17.DeclareAttackersAction\x12\x30\n\x10\x64\x65\x63lare_blockers\x18\x05 \x01(\x0b\x32\x16.DeclareBlockersAction\"o\n\nActionType\x12\t\n\x05START\x10\x00\x12\x08\n\x04PLAY\x10\x01\x12\x0c\n\x08\x41\x43TIVATE\x10\x02\x12\x15\n\x11\x44\x45\x43LARE_ATTACKERS\x10\x03\x12\x14\n\x10\x44\x45\x43LARE_BLOCKERS\x10\x04\x12\x11\n\rPASS_PRIORITY\x10\x05\"\x1c\n\x0cPlayerConfig\x12\x0c\n\x04\x64\x65\x63k\x18\x01 \x03(\t')



_CLIENTMESSAGE_CLIENTMESSAGETYPES = _descriptor.EnumDescriptor(
  name='ClientMessageTypes',
  full_name='ClientMessage.ClientMessageTypes',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CREATE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='JOIN', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTION', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEAVE', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='QUIT', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=246,
  serialized_end=321,
)

_JOINMESSAGE_CLIENTTYPE = _descriptor.EnumDescriptor(
  name='ClientType',
  full_name='JoinMessage.ClientType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PLAYER', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SPECTATOR', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=495,
  serialized_end=534,
)

_ACTIONMESSAGE_ACTIONTYPE = _descriptor.EnumDescriptor(
  name='ActionType',
  full_name='ActionMessage.ActionType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='START', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PLAY', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTIVATE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DECLARE_ATTACKERS', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DECLARE_BLOCKERS', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PASS_PRIORITY', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=774,
  serialized_end=885,
)


_CLIENTMESSAGE = _descriptor.Descriptor(
  name='ClientMessage',
  full_name='ClientMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message_type', full_name='ClientMessage.message_type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='create_message', full_name='ClientMessage.create_message', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='join_message', full_name='ClientMessage.join_message', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='action_message', full_name='ClientMessage.action_message', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CLIENTMESSAGE_CLIENTMESSAGETYPES,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=56,
  serialized_end=321,
)


_CREATEMESSAGE = _descriptor.Descriptor(
  name='CreateMessage',
  full_name='CreateMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='variant', full_name='CreateMessage.variant', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_players', full_name='CreateMessage.max_players', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=323,
  serialized_end=376,
)


_JOINMESSAGE = _descriptor.Descriptor(
  name='JoinMessage',
  full_name='JoinMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='game_id', full_name='JoinMessage.game_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='client_type', full_name='JoinMessage.client_type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player_config', full_name='JoinMessage.player_config', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _JOINMESSAGE_CLIENTTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=379,
  serialized_end=534,
)


_ACTIONMESSAGE = _descriptor.Descriptor(
  name='ActionMessage',
  full_name='ActionMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action_type', full_name='ActionMessage.action_type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='play', full_name='ActionMessage.play', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='activate_ability', full_name='ActionMessage.activate_ability', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='declare_attackers', full_name='ActionMessage.declare_attackers', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='declare_blockers', full_name='ActionMessage.declare_blockers', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ACTIONMESSAGE_ACTIONTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=537,
  serialized_end=885,
)


_PLAYERCONFIG = _descriptor.Descriptor(
  name='PlayerConfig',
  full_name='PlayerConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='deck', full_name='PlayerConfig.deck', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=887,
  serialized_end=915,
)

_CLIENTMESSAGE.fields_by_name['message_type'].enum_type = _CLIENTMESSAGE_CLIENTMESSAGETYPES
_CLIENTMESSAGE.fields_by_name['create_message'].message_type = _CREATEMESSAGE
_CLIENTMESSAGE.fields_by_name['join_message'].message_type = _JOINMESSAGE
_CLIENTMESSAGE.fields_by_name['action_message'].message_type = _ACTIONMESSAGE
_CLIENTMESSAGE_CLIENTMESSAGETYPES.containing_type = _CLIENTMESSAGE;
_JOINMESSAGE.fields_by_name['client_type'].enum_type = _JOINMESSAGE_CLIENTTYPE
_JOINMESSAGE.fields_by_name['player_config'].message_type = _PLAYERCONFIG
_JOINMESSAGE_CLIENTTYPE.containing_type = _JOINMESSAGE;
_ACTIONMESSAGE.fields_by_name['action_type'].enum_type = _ACTIONMESSAGE_ACTIONTYPE
_ACTIONMESSAGE.fields_by_name['play'].message_type = game_action_pb2._PLAYACTION
_ACTIONMESSAGE.fields_by_name['activate_ability'].message_type = game_action_pb2._ACTIVATEACTION
_ACTIONMESSAGE.fields_by_name['declare_attackers'].message_type = game_action_pb2._DECLAREATTACKERSACTION
_ACTIONMESSAGE.fields_by_name['declare_blockers'].message_type = game_action_pb2._DECLAREBLOCKERSACTION
_ACTIONMESSAGE_ACTIONTYPE.containing_type = _ACTIONMESSAGE;
DESCRIPTOR.message_types_by_name['ClientMessage'] = _CLIENTMESSAGE
DESCRIPTOR.message_types_by_name['CreateMessage'] = _CREATEMESSAGE
DESCRIPTOR.message_types_by_name['JoinMessage'] = _JOINMESSAGE
DESCRIPTOR.message_types_by_name['ActionMessage'] = _ACTIONMESSAGE
DESCRIPTOR.message_types_by_name['PlayerConfig'] = _PLAYERCONFIG

class ClientMessage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CLIENTMESSAGE

  # @@protoc_insertion_point(class_scope:ClientMessage)

class CreateMessage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CREATEMESSAGE

  # @@protoc_insertion_point(class_scope:CreateMessage)

class JoinMessage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _JOINMESSAGE

  # @@protoc_insertion_point(class_scope:JoinMessage)

class ActionMessage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ACTIONMESSAGE

  # @@protoc_insertion_point(class_scope:ActionMessage)

class PlayerConfig(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PLAYERCONFIG

  # @@protoc_insertion_point(class_scope:PlayerConfig)


# @@protoc_insertion_point(module_scope)
